version: 2

jobs:
  lint:
      working_directory: ~/react-smart-parallax
      docker:
        - image: circleci/node:8@sha256:455e78086f4abad6797c6b4e486450513e77867916acd44b5a8b861d840efaee
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Lint
            command: yarn run lint

  flow:
      working_directory: ~/react-smart-parallax
      docker:
        - image: circleci/node:8@sha256:455e78086f4abad6797c6b4e486450513e77867916acd44b5a8b861d840efaee
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Flow
            command: yarn run flow
  test:
      working_directory: ~/react-smart-parallax
      docker:
        - image: circleci/node:8@sha256:455e78086f4abad6797c6b4e486450513e77867916acd44b5a8b861d840efaee
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Run Tests & Check Coverage
            command: yarn run test:coverage

  build:
      working_directory: ~/react-smart-parallax
      docker:
        - image: circleci/node:8@sha256:455e78086f4abad6797c6b4e486450513e77867916acd44b5a8b861d840efaee
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Build package
            command: yarn run build

workflows:
  version: 2

  build:
    jobs:
      - lint
      - flow
      - test
      - build
