version: 2

jobs:
  lint:
      working_directory: ~/react-smart-parallax
      docker:
        - image: circleci/node:8@sha256:0ac63bc3d5a224deac83654a322a995332809c9f535434dfd195c26e7310ec3e
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Lint
            command: yarn run lint

  flow:
      working_directory: ~/react-smart-parallax
      docker:
        - image: circleci/node:8@sha256:0ac63bc3d5a224deac83654a322a995332809c9f535434dfd195c26e7310ec3e
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Flow
            command: yarn run flow
  test:
      working_directory: ~/react-smart-parallax
      docker:
        - image: circleci/node:8@sha256:0ac63bc3d5a224deac83654a322a995332809c9f535434dfd195c26e7310ec3e
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Run Tests & Check Coverage
            command: yarn run test:coverage

  build:
      working_directory: ~/react-smart-parallax
      docker:
        - image: circleci/node:8@sha256:0ac63bc3d5a224deac83654a322a995332809c9f535434dfd195c26e7310ec3e
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Build package
            command: yarn run build

workflows:
  version: 2

  build:
    jobs:
      - lint
      - flow
      - test
      - build
