version: 2

jobs:
  test-node6:
      working_directory: ~/materialize-react
      docker:
        - image: circleci/node:6
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Lint
            command: yarn run lint
        - run:
            name: Run Tests & Check Coverage
            command: yarn run test:coverage
        - run:
            name: Report Coverage
            command: yarn run report-coverage
  test-node8:
      working_directory: ~/materialize-react
      docker:
        - image: circleci/node:8
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Lint
            command: yarn run lint
        - run:
            name: Run Tests & Check Coverage
            command: yarn run test:coverage

workflows:
  version: 2

  test_and_deploy:
    jobs:
      - test-node6
      - test-node8
